spring:
  datasource:
    driver-class-name: 'com.mysql.cj.jdbc.Driver'
    password: ''
    url: 'jdbc:mysql://localhost:3306//appBd?createDatabaseIfNotExist=true'
    username: root
  jpa:
    database: 'MYSQL'
    hibernate:
      ddl-auto: 'update'
      naming:
        implicit-strategy: 'org.springframework.boot.orm.jpa.hibernate.SpringImplicitNamingStrategy'
    show-sql: true
