spring:
  datasource:
   
    password: ''
    
    username: root
  jpa:
    database: 'MYSQL'
    hibernate:
      ddl-auto: 'update'
      naming:
        implicit-strategy: 'org.springframework.boot.orm.jpa.hibernate.SpringImplicitNamingStrategy'
    show-sql: true
